use_frameworks!

platform :ios, '9.0'

target 'NXNetworking_Example' do
  pod 'NXNetworking', :path => '../'

  target 'NXNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
